from typing import Protocol

from app.engine.stockfish import AnalysisResult


class EngineProtocol(Protocol):
    """Interface that all chess engines must implement."""

    def start(self) -> None: ...
    def close(self) -> None: ...
    def analyze_position(self, fen: str, depth: int = 20, multipv: int = 3) -> AnalysisResult: ...
    def get_best_move(self, fen: str, time_limit: float = 1.0) -> tuple[str, str]: ...
    def play_move(self, fen: str, time_limit: float = 1.0) -> tuple[str, str, str]: ...
    def set_difficulty(self, tier: str) -> None: ...
